### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [quiet/quiet#1]
Would you like to add more error handling for return values from functions like the following?
- [fwrite](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html) ⇒ [recv_all](https://github.com/brian-armstrong/quiet/blob/8852985af49035970a999ae10653a9edad92303a/programs/decode_file.c#L30)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [encoder_ofdm_create](https://github.com/brian-armstrong/quiet/blob/99a95fb1ebc1999de8ea6bd975f72c96c9daefcb/src/encoder.c#L3)

**Comment by brian-armstrong** [comment]
This sounds like a good priority for my next steps. I punted on how I wanted to handle malloc everywhere. Now that my library is out there I need to go back and clean all of that up :)

Thanks for the issue

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by brian-armstrong** [comment]
My tentative plan is to create a module-level errno-like object. I believe this mostly applies to creation and send/recv. I don't anticipate surfacing errors from emit/consume. There's a few places where those functions presently can call realloc, but in future cleanup work I'd like to remove those calls.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

**Comment by brian-armstrong** [comment]
Good idea. I'll see if I can add a new rule to the cmake to do clang static analysis.
