### ISSUE TITLE
Quiet

### ISSUE THREAD

**Issue by emansih** [quiet/quiet#17]
Hi. I have an application in mind to make that requires cross platform. By using org.quietmodem.Quiet on Android and quiet on Window, will I be able to send data between them even thought they use different libraries? Thanks!

**Comment by brian-armstrong** [comment]
@emansih Hi!

Yes, that's right. As long as two modems share the same profile, they will communicate.

I haven't tested libquiet on Windows yet, so you may be a bit of a guinea pig. I expect it to work once it's built but the build process might need some tweaks. If you do run into any issues please don't hesitate to put them here and I will help fix them

**Comment by emansih** [comment]
Sure, i will be happy to test it.

**Comment by emansih** [comment]
I didn't build the binary on windows though. I built it on Debian Jessie and have the .so file to use it on windows

**Comment by emansih** [comment]
https://drive.google.com/open?id=0B5iTdQV5w5DwTl9vOHVUaF9QQzA

I have the deb file for amd64, you might want to add to the release page just in case anyone doesn't want to build it.
