### ISSUE TITLE
Fail to encode the file

### ISSUE THREAD

**Issue by gamejzb** [quiet/quiet#19]
HI，
I want to encode  text to a .wav file.
$ echo "test" >> 1.txt
$ ./quiet_encode_file audible 1.txt
it  successfully generate a .wav file but empty data(only 80 bytes).
  error: fec_get_enc_msg_length(), convolutional codes unavailable (install libfec)
The error seems i need install libfec, but i have installed libfec without any error.

Maybe i need configure some  extra parameters ？

Thanks.

**Comment by brian-armstrong** [comment]
Hi @gamejzb

Now that you have libfec, you'll need to rerun configure/make/make install on liquid-dsp so that it builds and installs its libfec component

Sorry for the inconvenience :)

**Comment by gamejzb** [comment]
@brian-armstrong  yes, fixed it, thank you very much.

**Comment by brian-armstrong** [comment]
Glad it works. Have fun :)
