### ISSUE TITLE
After installing libfec, liquid-dsp cannot find libfec 

### ISSUE THREAD

**Issue by sanjeev1994** [quiet/quiet#20]
installed libfec and then I configured liquid-dsp, in the output of ./configure I am getting these lines about libfec
checking fec.h usability... no
checking fec.h presence... no
checking for fec.h... no

/usr/local/include/ in this path I am able to find fec.h file after instaling libfec.

Please help me with this issue.

thanks.

**Comment by brian-armstrong** [comment]
Hi @sanjeev1994 

Can you search config.log in liquid-dsp/ directory for "fec.h" and post any nearby lines here? It will show the test it's doing first "checking for fec.h usability" and then the test it tries and then the result. If you can paste the entries for fec.h, I think I can help you diagnose what's wrong
