### ISSUE TITLE
libliquid.so: not found

### ISSUE THREAD

**Issue by nikola3244** [quiet/quiet#24]
So, after installing all required dependencies and `quiet`, I am left with one final issue: `quiet_encode_file: error while loading shared libraries: libliquid.so: cannot open shared object file: No such file or directory`.

But, `$ whereis libliquid.so` returns:
`libliquid: /usr/local/lib/libliquid.so /usr/local/lib/libliquid.a`

I have also done `# ldconfig`. Error is still there.

System: `Linux archlinux 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux`

**Comment by yetanothergeek** [comment]
What happens if you run:

LD_LIBRARY_PATH=/usr/local/lib quiet_encode_file

If that works, you may need to add /usr/local/lib to your /etc/ld.so.conf* file(s) and re-run ldconfig.

**Comment by nikola3244** [comment]
That fixes it! Thank you!
