### ISSUE TITLE
quiet_encode_file problem,failed to read profile 

### ISSUE THREAD

**Issue by tangzhimiao** [quiet/quiet#26]
Hello, I have a problem that can not be solved, I have installed all the dependencies and quiet in Linux environment, running the command (quiet_encode_files   quiet-profiles.json   in.txt) in the directory quiet-master/build/bin
Failed to read profile quiet-profiles.json from /usr/local/share/quiet/quiet-profiles.json will be obtained

Please help me with this issue.

thanks.

**Comment by brian-armstrong** [comment]
Hi @tangzhimiao 

You just need to run `make install`. The encode file program is looking for the profiles file at the install location, but it can't find it because you haven't installed yet. This is a little inconvenient, sorry.

**Comment by tangzhimiao** [comment]
I have executed the make install command, the installation path is in /usr/local/share/quiet/quiet-profiles.json, but it will still encounter the same problem, and I also give quiet-profiles.json permissions. Please help me to solve.
thanks.

**Comment by brian-armstrong** [comment]
@tangzhimiao Oh, I see. You'll want to call quiet_encode_file with the name of one of the profiles in the json file, not the name of the json file itself. This could be `audible`, `ultrasonic`, etc

**Comment by tangzhimiao** [comment]
I can't catch your meaning. Can you explain?

**Comment by brian-armstrong** [comment]
Have a look at the file those profiles are in https://github.com/quiet/quiet/blob/master/quiet-profiles.json

It's a JSON file with a top-level object, where each key refers to some specific set of configuration. So for example, one of those keys is `audible` that sets up an audible modem. The parameter you're passing here has to be one of those keys.

**Comment by tangzhimiao** [comment]
Thank you. I've solved that problem, successfully generated the.Wav file and played the sound. But when I decoded, I found that the direct decoding was the newly generated.Wav file (on a computer test). Could you tell me their execution commands?

**Comment by brian-armstrong** [comment]
I'm not entirely sure I understand, but if you're using quiet_decode_file, it expects the file to be saved as encoded.wav.

If you just want to run a test with speaker/microphone, then you might find it easier to just use quiet_encode_soundcard/quiet_decode_soundcard rather than dealing with the WAV files

**Comment by tangzhimiao** [comment]
I did generate the encoded.wav. that I thought I should be doing the wrong instructions when performing the next step. How should I do it?

**Comment by brian-armstrong** [comment]
something like
`quiet_encode_file audible in.txt` should generate encoded.wav
`quiet_decode_file audible` should decode encoded.wav

If that's what you mean?
