### ISSUE TITLE
Error when encoding "hello"

### ISSUE THREAD

**Issue by foamliu** [quiet/quiet#41]
Thanks for the awesome work!

I've successfully built the code in Ubuntu 18.04, however when I run the sample with following command:
./quiet_encode_file ultrasonic test.txt
It returns error: fec_get_msg_length(), convolutional codes unavailable (install libfec)
I am quite sure that libfec has been installed already.
Is it possible that we can take a look at this issue together? 

The following is screenshot:
![image](https://user-images.githubusercontent.com/14009435/59730690-ec039f00-9275-11e9-8951-0de6c9cdfb49.png)

**Comment by brian-armstrong** [comment]
Hello,

You will need to rebuild liquid now that you have libfec. You will probably need to re-./configure && make && make install it.

Brian

**Comment by foamliu** [comment]
@brian-armstrong It works perfectly, thank you very much!
