### ISSUE TITLE
Decimation with uncorrelated sampling instants

### ISSUE THREAD

**Issue by gopik** [quiet/quiet#7]
At https://github.com/quiet/quiet/blob/master/src/demodulator.c#L48, decimation is performed by a simple dot product and taking the 0th sample. Shouldn't we be using the sample with maximum value (which may not be at index 0 if there's an unknown delay in the sample stream)

**Comment by brian-armstrong** [comment]
Hi,

Looking at the source of the decimator, you can see that it pushes all the samples into a sliding sample window and then finds the dotproduct. Although it does run this dotproduct when it hits the 0th sample in that loop, it's reading all `k` samples out of the sliding window. The first time this runs, it'll see all 0s. After that, it'll see the past `k` samples each time, delayed by the group delay of the filter.

**Comment by brian-armstrong** [comment]
Also, I realize now that `modulator/demodulator` is poor naming here on my part. These objects are combination interpolation+mixer and downmixer+decimation, respectively.

**Comment by gopik** [comment]
I tried the sliding window behavior of decimator and i see that the window slides by symbols and not by samples. Here's an example that I tried:

#include "liquid.h"
#include <stdio.h>                                                                                                                                           #include <complex.h>                                                                                                                                         
                                                                                                                                                             
int main(int argc, char** argv) {                                                                                                                            
  float h[15] = {0}; // 15 taps filter, 3 samples per symbol                                                                                                                                         
  h[0] = 1.0; // pass through                                                                                                                                                    decim_crcf decim = decim_crcf_create(3, h, 15);                                                                                                            
                                                                                                                                                             
  float complex samples[30];                                                                                                                                for (int i = 0; i < 30; ++i) {                                                                                                                             
    samples[i] = i;                                                                                                                                            }                                                                                                                                                          

// samples contain 10 symbols where each symbol is 3 samples each.                                                                                                                                                             
  for (int i = 0; i < 30; i += 3) {                                                                                                                          
    float complex out;                                                                                                                                       
    decim_crcf_execute(decim, &samples[i], &out, 0);                                                                                                         
    printf("%f\n", creal(out));                                                                                                                              
  }                                                                                                                                                          
}                                                                                                                                                            

Here's the output I get:   
0.000000
3.000000
6.000000
9.000000
12.000000
15.000000
18.000000
21.000000
24.000000
27.000000

I expected to see all samples, but only getting first sample of each symbol.
This means, in the decimation, we are ignoring sub symbol offset, is that correct?

Thanks,
Gopi

**Comment by brian-armstrong** [comment]
That's correct -- for this part of the process, we aren't concerned with the phase for any carriers passing through. The framesync objects perform a full synchronization process, which includes finding and correcting the modem phase. Since we run those in the stage immediately after this decimation, we don't need to worry about that here. It's sufficient to just perform sample rate decimation here.

**Comment by gopik** [comment]
Thanks, this makes sense.
